# éƒ¨ç½² VitePress æ–‡æ¡£åˆ° Github Pages

name: ğŸ’¼ Deploy Foreslash Design VitePress Document

on:
  push:
    branches:
      - main
    paths:
      - "packages/docs/**"

# è®¾ç½® GITHUB_TOKEN çš„æƒé™ï¼Œä»¥å…è®¸éƒ¨ç½²åˆ° GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# ä¸å…è®¸åŒæ—¶è¿›è¡Œå¤šä¸ªéƒ¨ç½²ï¼Œè·³è¿‡éæ­£åœ¨è¿è¡Œã€éæœ€æ–°é˜Ÿåˆ—çš„è¿è¡Œé˜Ÿåˆ—ï¼Œä¸”ä¸å–æ¶ˆæ­£åœ¨è¿è¡Œçš„å·¥ä½œæµ
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  # æ„å»º
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“‹ï¸ Checkout # åˆ‡å‡ºåˆ†æ”¯
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: ğŸ“¦ Install pnpm # å®‰è£… pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.14.0
      - name: ğŸ“¦ Setup Node # å®‰è£… Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: ğŸ“¦ Setup Pages # å®‰è£… Github Pages
        uses: actions/configure-pages@v4
      - name: ğŸ“¦ Install dependencies # å®‰è£…ä¾èµ–
        run: pnpm i --frozen-lockfile
      - name: ğŸ—ï¸ Build with VitePress # ç¼–è¯‘ VP
        run: pnpm run build # touch ./docs/.vitepress/dist/.nojekyll
      - name: ğŸš€ Upload artifact # ä¸Šä¼ ç¼–è¯‘ç»“æœ
        uses: actions/upload-pages-artifact@v3
        if: | # ä»…åœ¨ Moushudyx ä¸‹å‘å¸ƒ, é˜²æ­¢ fork åè¯¯æ“ä½œ
          startsWith(github.repository, 'Moushudyx')
        with:
          path: ./packages/docs/.vitepress/dist
  # éƒ¨ç½²
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: ğŸš€ Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
